version: 2
jobs:
  build-32:
    docker:
      - image: jmgao/ubuntu-cosmic-mingw-w64-rust:latest
    steps:
      - checkout
      - run:
          name: Build 32-bit
          command: /root/.cargo/bin/cargo build --target i686-pc-windows-gnu --tests
      - run:
          name: Run 32-bit tests
          command: wine target/i686-pc-windows-gnu/debug/integration_test-*.exe
  build-64:
    docker:
      - image: jmgao/ubuntu-cosmic-mingw-w64-rust:latest
    steps:
      - checkout
      - run:
          name: Build 64-bit
          command: /root/.cargo/bin/cargo build --target x86_64-pc-windows-gnu --tests
      - run:
          name: Run 64-bit tests
          command: wine target/x86_64-pc-windows-gnu/debug/integration_test-*.exe
  build-linux:
    docker:
      - image: jmgao/ubuntu-cosmic-mingw-w64-rust:latest
    steps:
      - checkout
      - run:
          name: Build Linux
          command: /root/.cargo/bin/cargo build --target x86_64-unknown-linux-gnu --tests

workflows:
  version: 2
  build:
    jobs:
      - build-32
      - build-64
      - build-linux
